apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dep
  name: my-dep
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-dep
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
      - image: httpd:alpine3.22
        name: httpd
        command: ["/bin/bash", "-c"] #override default command
        args: ["sleep 5; exit 1"] #sleep for 5 seconds and then exit with code 1: error
